// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import * as fs from "fs";
import * as path from "path";
import { defineConfig } from "prisma/config";

// Load the correct env file based on environment.
// In local dev (no Docker), .env.development has the Tailscale IP.
// In Docker/production, .env has the Docker-internal 'db' hostname.
const isDev = process.env.NODE_ENV !== "production";
const devEnvPath = path.resolve(process.cwd(), ".env.development");

if (isDev && fs.existsSync(devEnvPath)) {
  const { config } = await import("dotenv");
  config({ path: devEnvPath, override: true });
} else {
  const { config } = await import("dotenv");
  config();
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
